insert into acces_ar_definitions (category, label, has_precision, precision_label, status) values
-- MATÉRIELS (16)
('Matériels', 'Supports de cours lisibles et aérés (Arial 12, interlignes, titres en évidence, pages numérotées)', false, null, 'active'),
('Matériels', 'Taille de police plus grande (Arial 14)', false, null, 'active'),
('Matériels', 'Notes de cours et évaluations avec place suffisante pour écrire', false, null, 'active'),
('Matériels', 'Notes de cours et évaluations uniquement en recto', false, null, 'active'),
('Matériels', 'Objets silencieux à manipuler (aide attentionnelle)', false, null, 'active'),
('Matériels', 'Écouteurs avec musique douce autorisés', false, null, 'active'),
('Matériels', 'Casque anti-bruit / boules quies / écouteurs sans musique autorisés', false, null, 'active'),
('Matériels', 'Tables de multiplication à disposition', false, null, 'active'),
('Matériels', 'Calculatrice', false, null, 'active'),
('Matériels', 'Faire effectuer les calculs en colonnes (pas en ligne)', false, null, 'active'),
('Matériels', 'Google Lens (traduction ou lecture de textes)', false, null, 'active'),
('Matériels', 'Prendre des photos du tableau', false, null, 'active'),
('Matériels', 'Dictionnaire (imagé) en ligne pour le vocabulaire', false, null, 'active'),
('Matériels', 'Fiches outils (lexique, procédures, formules, référentiel…) y compris lors des évaluations', false, null, 'active'),
('Matériels', 'Outil numérique (iPad / ordinateur) avec envoi des cours', false, null, 'active'),
('Matériels', 'Latte de lecture', false, null, 'active'),
-- PÉDAGOGIQUES (24)
('Pédagogiques', 'Fournir le cours complété en format numérique ou papier', false, null, 'active'),
('Pédagogiques', 'S''assurer que le cours est convenablement complété par l''élève', false, null, 'active'),
('Pédagogiques', 'Support visuel en soutien aux explications orales', false, null, 'active'),
('Pédagogiques', 'Répéter l''info importante au moins 2 fois / la noter au tableau', false, null, 'active'),
('Pédagogiques', 'Expliciter les mots potentiellement incompris', false, null, 'active'),
('Pédagogiques', 'Privilégier les textes simples et courts (si lecture non évaluée)', false, null, 'active'),
('Pédagogiques', 'Lire oralement les consignes et les textes (si lecture non évaluée)', false, null, 'active'),
('Pédagogiques', 'Favoriser les réponses orales', false, null, 'active'),
('Pédagogiques', 'Favoriser les QCM / vrai-faux (sans cotation négative)', false, null, 'active'),
('Pédagogiques', 'Une consigne à la fois', false, null, 'active'),
('Pédagogiques', 'Vérifier la compréhension des consignes', false, null, 'active'),
('Pédagogiques', 'Explications plus approfondies / reformulations', false, null, 'active'),
('Pédagogiques', 'Renforcements positifs et aide à la gestion du stress', false, null, 'active'),
('Pédagogiques', 'Relances attentionnelles', false, null, 'active'),
('Pédagogiques', 'Feedbacks fréquents, spécifiques et immédiats', false, null, 'active'),
('Pédagogiques', 'Parler lentement, face à l''élève, dans le silence', false, null, 'active'),
('Pédagogiques', 'Laisser un temps de traitement de l''information', false, null, 'active'),
('Pédagogiques', 'Ne pas pénaliser l''orthographe et la graphie si non évaluées', false, null, 'active'),
('Pédagogiques', 'Faire surligner les éléments importants dans la théorie', false, null, 'active'),
('Pédagogiques', 'Noter pour l''élève si la situation le nécessite', false, null, 'active'),
('Pédagogiques', 'Favoriser la qualité à la quantité (nombre d''items réduit)', false, null, 'active'),
('Pédagogiques', 'Dissocier le moment d''explication et le moment de copie', false, null, 'active'),
('Pédagogiques', 'Pas de prise de note orale/sous dictée → faire recopier un support écrit', false, null, 'active'),
('Pédagogiques', 'Éviter de faire lire l''élève à voix haute sans préparation', false, null, 'active'),
-- ORGANISATIONNELS (8)
('Organisationnels', 'Tiers-temps supplémentaire', false, null, 'active'),
('Organisationnels', 'Pause après X minutes', true, 'Durée de la pause (minutes)', 'active'),
('Organisationnels', 'Placer l''élève face au tableau', false, null, 'active'),
('Organisationnels', 'S''assurer qu''il range ses feuilles au bon endroit', false, null, 'active'),
('Organisationnels', 'Compléter le journal de classe / vérifier la prise en note', false, null, 'active'),
('Organisationnels', 'Placer l''élève proche du prof', false, null, 'active'),
('Organisationnels', 'Dispensé des auditions → travail sur base du texte écrit', false, null, 'active'),
('Organisationnels', 'Utilisation de la dictée vocale + correcteur d''orthographe', false, null, 'active')
on conflict (label) do nothing;
